export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_SORT_BY_SUCCESS = 'SET_SORT_BY_SUCCESS';

export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_NAME_SUCCESS = 'SORT_BY_NAME_SUCCESS';

export const SORT_BY_AVAILABILITY = 'SORT_BY_AVAILABILITY';
export const SORT_BY_AVAILABILITY_SUCCESS = 'SORT_BY_AVAILABILITY_SUCCESS';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const FETCH_ITEM_AVAILABILITY = 'FETCH_ITEM_AVAILABILITY';
export const FETCH_ITEM_AVAILABILITY_SUCCESS = 'FETCH_ITEM_AVAILABILITY_SUCCESS';