export const SORT_INVENTORY = 'SORT_INVENTORY';

export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';

export const FETCH_INVENTORY = 'FETCH_INVENTORY';

export const RECEIVED_INVENTORY = 'RECEIVED_INVENTORY';

export const FETCH_INVENTORY_ERROR = 'FETCH_INVENTORY_ERROR';