export const SORT_BY = 'SORT_BY';

export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';

export const FETCH_INVENTORY = 'FETCH_INVENTORY';

export const RECEIVED_INVENTORY = 'RECEIVED_INVENTORY';

export const FETCH_INVENTORY_ERROR = 'FETCH_INVENTORY_ERROR';